-- MAID's built-in look, the one in effect when no theme is set. It is the same table as default_styles() in
-- core/src/settings.cpp (a test keeps them equal), so this file is the place to read every role and its default,
-- and a starting point for a theme of your own: copy it to ~/.config/maid/themes/NAME.lua, edit, :theme NAME.
-- Colours are FTXUI names, "#rrggbb" or 0-255; italic renders as dim. docs/themes.md
return {
  name = "default",
  background = "dark",
  styles = {
    -- transcript
    user = { bold = true },
    assistant = {},
    thinking = { dim = true },
    tool = { fg = "cyan" },
    tool_ok = { fg = "gray_dark" },
    tool_err = { fg = "red" },
    notice = { fg = "yellow" },
    error = { fg = "red_light" },
    shell = { fg = "green_light" },
    -- markdown, applied on top of the entry's style
    md_heading = { fg = "magenta", bold = true },
    md_bold = { bold = true },
    md_italic = { italic = true },
    md_code = { fg = "yellow_light" },
    md_code_block = { fg = "white", bg = "#1c1c1c" },
    md_link = { fg = "blue_light", underline = true },
    md_url = { fg = "gray_dark" },
    md_quote = { fg = "gray", italic = true },
    md_bullet = { fg = "cyan" },
    md_rule = { fg = "gray_dark" },
    -- the nvim highlighter's captures (highlight = "nvim"), applied like the markdown styles
    hl_keyword = { fg = "blue_light", bold = true },
    hl_string = { fg = "green" },
    hl_comment = { fg = "gray", italic = true },
    hl_heading = { fg = "magenta", bold = true },
    hl_code = { fg = "yellow_light" },
    -- diffs: the approval preview and tool output that is a diff
    diff_added = { fg = "green" },
    diff_removed = { fg = "red" },
    diff_hunk = { dim = true },
    -- chrome
    input = {},
    input_prompt_insert = { fg = "green" },
    input_prompt_normal = { fg = "blue" },
    separator = { fg = "gray_dark" },
    focus = { fg = "cyan" },
    visual = { bg = "#3a3a5c", inverted = true },
    search = { fg = "black", bg = "yellow" },
    cursor_line = { bg = "#262626" },
    status = {},
    status_insert = { fg = "green", bold = true, inverted = true },
    status_normal = { fg = "blue", bold = true, inverted = true },
    status_visual = { fg = "magenta", bold = true, inverted = true },
    status_dim = { dim = true },
    mode_manual = { fg = "blue", bold = true },
    ["mode_auto-read"] = { fg = "cyan", bold = true },
    mode_edit = { fg = "yellow", bold = true },
    mode_auto = { fg = "red", bold = true },
    mode_plan = { fg = "green", bold = true },
    harness_armed = { fg = "green" },
    harness_tripped = { fg = "red", bold = true },
    remote = { fg = "red_light", bold = true },
    approval = { fg = "yellow" },
  },
}
